// Comprehensive country to language mapping
export const countryLanguageMap = {
    'Afghanistan': 'Pashto',
    'Albania': 'Albanian',
    'Algeria': 'Arabic',
    'Andorra': 'Catalan',
    'Angola': 'Portuguese',
    'Argentina': 'Spanish',
    'Armenia': 'Armenian',
    'Australia': 'English',
    'Austria': 'German',
    'Azerbaijan': 'Azerbaijani',
    'Bahamas': 'English',
    'Bangladesh': 'Bengali',
    'Belgium': 'Dutch',
    'Belize': 'English',
    'Benin': 'French',
    'Bhutan': 'Dzongkha',
    'Bolivia': 'Spanish',
    'Bosnia & Herzegovina': 'Bosnian',
    'Botswana': 'English',
    'Brazil': 'Portuguese',
    'Bulgaria': 'Bulgarian',
    'Canada': 'English',
    'Chile': 'Spanish',
    'China': 'Mandarin Chinese',
    'Colombia': 'Spanish',
    'Costa Rica': 'Spanish',
    'Croatia': 'Croatian',
    'Cuba': 'Spanish',
    'Cyprus': 'Greek',
    'Czech Republic': 'Czech',
    'Denmark': 'Danish',
    'Dominican Republic': 'Spanish',
    'Ecuador': 'Spanish',
    'Egypt': 'Arabic',
    'El Salvador': 'Spanish',
    'Estonia': 'Estonian',
    'Ethiopia': 'Amharic',
    'Finland': 'Finnish',
    'France': 'French',
    'Georgia': 'Georgian',
    'Germany': 'German',
    'Ghana': 'English',
    'Greece': 'Greek',
    'Guatemala': 'Spanish',
    'Haiti': 'Haitian Creole',
    'Honduras': 'Spanish',
    'Hungary': 'Hungarian',
    'Iceland': 'Icelandic',
    'India': 'Hindi',
    'Indonesia': 'Indonesian',
    'Iran': 'Persian (Farsi)',
    'Iraq': 'Arabic',
    'Ireland': 'English',
    'Israel': 'Hebrew',
    'Italy': 'Italian',
    'Jamaica': 'English',
    'Japan': 'Japanese',
    'Jordan': 'Arabic',
    'Kazakhstan': 'Kazakh',
    'Kenya': 'English',
    'Kuwait': 'Arabic',
    'Kyrgyzstan': 'Kyrgyz',
    'Laos': 'Lao',
    'Latvia': 'Latvian',
    'Lebanon': 'Arabic',
    'Lithuania': 'Lithuanian',
    'Luxembourg': 'Luxembourgish',
    'Malaysia': 'Malay',
    'Maldives': 'Dhivehi',
    'Mali': 'French',
    'Mexico': 'Spanish',
    'Moldova': 'Romanian',
    'Mongolia': 'Mongolian',
    'Morocco': 'Arabic',
    'Nepal': 'Nepali',
    'Netherlands': 'Dutch',
    'New Zealand': 'English',
    'Nigeria': 'English',
    'North Korea': 'Korean',
    'Norway': 'Norwegian',
    'Oman': 'Arabic',
    'Pakistan': 'Urdu',
    'Panama': 'Spanish',
    'Paraguay': 'Spanish',
    'Peru': 'Spanish',
    'Philippines': 'Filipino',
    'Poland': 'Polish',
    'Portugal': 'Portuguese',
    'Qatar': 'Arabic',
    'Romania': 'Romanian',
    'Russia': 'Russian',
    'Saudi Arabia': 'Arabic',
    'Serbia': 'Serbian',
    'Singapore': 'English',
    'Slovakia': 'Slovak',
    'Slovenia': 'Slovene',
    'South Africa': 'English',
    'South Korea': 'Korean',
    'Spain': 'Spanish',
    'Sri Lanka': 'Sinhala',
    'Sweden': 'Swedish',
    'Switzerland': 'German',
    'Syria': 'Arabic',
    'Taiwan': 'Mandarin Chinese',
    'Thailand': 'Thai',
    'Turkey': 'Turkish',
    'Ukraine': 'Ukrainian',
    'United Arab Emirates': 'Arabic',
    'UAE': 'Arabic',
    'United Kingdom': 'English',
    'UK': 'English',
    'United States': 'English',
    'USA': 'English',
    'Vietnam': 'Vietnamese',
    'Yemen': 'Arabic',
    'Zambia': 'English',
    'Zimbabwe': 'English',
};

// Country to currency mapping
export const countryCurrencyMap = {
    'Afghanistan': { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
    'Albania': { code: 'ALL', symbol: 'L', name: 'Albanian Lek' },
    'Algeria': { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar' },
    'Argentina': { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
    'Australia': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
    'Austria': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Bangladesh': { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
    'Belgium': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Brazil': { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
    'Bulgaria': { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
    'Canada': { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
    'Chile': { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
    'China': { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
    'Colombia': { code: 'COP', symbol: '$', name: 'Colombian Peso' },
    'Croatia': { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna' },
    'Czech Republic': { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
    'Denmark': { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
    'Egypt': { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
    'Finland': { code: 'EUR', symbol: '€', name: 'Euro' },
    'France': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Germany': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Greece': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Hungary': { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
    'Iceland': { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
    'India': { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
    'Indonesia': { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
    'Iran': { code: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
    'Iraq': { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
    'Ireland': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Israel': { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
    'Italy': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Japan': { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
    'Jordan': { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar' },
    'Kazakhstan': { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
    'Kenya': { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
    'Kuwait': { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
    'Malaysia': { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
    'Mexico': { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
    'Morocco': { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
    'Nepal': { code: 'NPR', symbol: 'रू', name: 'Nepalese Rupee' },
    'Netherlands': { code: 'EUR', symbol: '€', name: 'Euro' },
    'New Zealand': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
    'Nigeria': { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
    'North Korea': { code: 'KPW', symbol: '₩', name: 'North Korean Won' },
    'Norway': { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
    'Oman': { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
    'Pakistan': { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
    'Philippines': { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
    'Poland': { code: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
    'Portugal': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Qatar': { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
    'Romania': { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
    'Russia': { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
    'Saudi Arabia': { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
    'Serbia': { code: 'RSD', symbol: 'дин', name: 'Serbian Dinar' },
    'Singapore': { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
    'Slovakia': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Slovenia': { code: 'EUR', symbol: '€', name: 'Euro' },
    'South Africa': { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
    'South Korea': { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
    'Spain': { code: 'EUR', symbol: '€', name: 'Euro' },
    'Sri Lanka': { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
    'Sweden': { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
    'Switzerland': { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
    'Syria': { code: 'SYP', symbol: '£S', name: 'Syrian Pound' },
    'Taiwan': { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar' },
    'Thailand': { code: 'THB', symbol: '฿', name: 'Thai Baht' },
    'Turkey': { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
    'Ukraine': { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
    'United Arab Emirates': { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
    'UAE': { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
    'United Kingdom': { code: 'GBP', symbol: '£', name: 'British Pound' },
    'UK': { code: 'GBP', symbol: '£', name: 'British Pound' },
    'United States': { code: 'USD', symbol: '$', name: 'US Dollar' },
    'USA': { code: 'USD', symbol: '$', name: 'US Dollar' },
    'Vietnam': { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
    'Yemen': { code: 'YER', symbol: '﷼', name: 'Yemeni Rial' },
    'Zambia': { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
    'Zimbabwe': { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar' },
};

// All supported languages (unique list)
export const allLanguages = [
    'Albanian', 'Amharic', 'Arabic', 'Armenian', 'Azerbaijani',
    'Bengali', 'Bosnian', 'Bulgarian', 'Catalan', 'Croatian',
    'Czech', 'Danish', 'Dhivehi', 'Dutch', 'Dzongkha',
    'English', 'Estonian', 'Filipino', 'Finnish', 'French',
    'Georgian', 'German', 'Greek', 'Haitian Creole', 'Hebrew',
    'Hindi', 'Hungarian', 'Icelandic', 'Indonesian', 'Italian',
    'Japanese', 'Kazakh', 'Korean', 'Kyrgyz', 'Lao',
    'Latvian', 'Lithuanian', 'Luxembourgish', 'Malay', 'Mandarin Chinese',
    'Mongolian', 'Nepali', 'Norwegian', 'Pashto', 'Persian (Farsi)',
    'Polish', 'Portuguese', 'Romanian', 'Russian', 'Serbian',
    'Sinhala', 'Slovak', 'Slovene', 'Spanish', 'Swedish',
    'Thai', 'Turkish', 'Ukrainian', 'Urdu', 'Vietnamese'
];

// All countries list
export const allCountries = Object.keys(countryLanguageMap).sort();

// Helper function to get language for country
export function getLanguageForCountry(country) {
    return countryLanguageMap[country] || 'English';
}

// Helper function to get currency for country
export function getCurrencyForCountry(country) {
    return countryCurrencyMap[country] || { code: 'USD', symbol: '$', name: 'US Dollar' };
}

// Helper function to format duration
export function formatDuration(days) {
    if (days < 7) return `${days} days (Short stay)`;
    if (days < 30) return `${days} days (${Math.floor(days / 7)} weeks)`;
    if (days < 365) return `${days} days (${Math.floor(days / 30)} months)`;
    return `${days} days (${Math.floor(days / 365)} years)`;
}
